### ISSUE TITLE
Sometimes writing tags causes invalid files

### ISSUE THREAD

**Issue by elomatreb** [jamesrhurst/rust-metaflac#8]
I was writing a script to add lyrics to the FLAC files in my library, and I noticed that it would metadata errors on some of the files. The lyrics written get cut off, and sometimes it breaks other tags and causes other metadata consumers to refuse the file completely. I'm not familiar enough with the FLAC format to tell exactly what's going wrong here though.

I have a [minimal-ish demo](https://github.com/elomatreb/metaflac-issue), but I couldn't make it work on "bare" FLAC files (just containing a sine or something like that), it only seemed to happen on actual music files, so I had to include one in the repo.

**Comment by jameshurst** [comment]
The issue was that the comments length that was written was incorrect when there were multiple comments of the same type. I've published 0.1.10 which has a fix this.

**Comment by elomatreb** [comment]
This works reliably now, thanks a lot!
